name: God and You - Devotions
description: Articles to uplift and encourage
url: devotionalarticles.com

markdown: redcarpet
pygments: true

exclude: [Gemfile, Gemfile.lock]

prose:
  rooturl: "_posts"
  siteurl: "https://devotionalarticles.com"
  media: "img"
  metadata:
    _posts:
       - name: "layout"
         field:
           element: "hidden"
           value: "post"
       - name: "title"
         field:
           element: "text"
           label: "Title"
       - name: "date"
         field:
           element: "text"
           label: "Date"
       - name: "category"
         field:
           element: "select"
           label: "Category"
           options: {"name":"article", "value":"article"}
       - name: "tags"
         field:
           element: "multiselect"
           label: "Add Tags"
           placeholder: "Choose Tags"
           alterable: true
       - name: "author"
         field:
           element: "text"
           label: "Author"
           value: "Daniel Baker"
       - name: "published"
         field:
           element: "button"
           label: "Published"
           on: "Published"
           off: "Unpublished"
